primary_hc <- c(
  "Rural Health Clinic",
  "Primary Health Care Unit +",
  "Rural Health Centre",
  "Health Centre IV",
  "Health Centre II",
  "Health Centre III",
  "Unité de Soins Périphérique",
  "Primary Health Care Centre",
  "Primary Health Care Unit",
  "Community Health Centre (After hours)",
  "Community Health Centre/Clinic",
  "Satellite Clinic",
  "Community Health Post",
  "Postos de Saúde Comunitária",
  "Secondary Health Post",
  "DISPENSARY",
  "Model Primary Health Centre",
  "Federal Medical Centre",
  "Comprehensive Health Centre",
  "Basic Health Centre",
  "Model Health Centre",
  "Primary Health Centre",
  "Health Hut",
  "Integrated Health Centre",
  "Centro de Saúde Urbano A",
  "Centro de Saúde Urbano B",
  "Centro de Saúde Urbano C",
  "Centro de Saúde Rural II",
  "Centro de Saúde Rural I",
  "Medi-Clinic",
  "Family Health Clinic",
  "Area Health Centre",
  "Referral Health Centre",
  "Health Post/Dispensary",
  "Filter Clinic",
  "Dispensary",
  "Community-based Health Planning and Services",
  "Health Centre (major)",
  "Health Centre (minor)",
  "Medical Centre",
  "Health post",
  "Nucleas Health Centre",
  "Clinic with Maternity",
  "Public Health Unit",
  "Clinic without Maternity",
  "Mini Clinic",
  "Health Station",
  "Poste De Santé",
  "Centre de Santé Municipal",
  "Centre de Santé de Référence",
  "Centre de Santé",
  "Centre de Santé Urbain",
  "Centre de Santé Rural",
  "Centre Médico-Urbain",
  "Poste de Santé",
  'Centre de Santé "D"',
  'Centre de Santé "A"',
  'Centre de Santé "B"',
  'Centre de Santé "E"',
  'Centre de Santé "C"',
  "Centre de Sante",
  "Poste de santé",
  "Postos Sanitários",
  "Centre Medical d’Arrondissement",
  "Centre de Santé Intégré",
  "Centre de Santé et de Promotion Sociale",
  "Health Post",
  "Centre Médico-social",
  "Centre de Santé Central",
  "Unites de Santé de village",
  "Centro de Santé de Circonscription Urbaine",
  "Unites de Santé de Village",
  "Centre Médical",
  "Centre de Santé de Sous-Prefecture",
  "Dispensaire",
  "Centre de Santé d’Arrondissement",
  "Community Health Centre",
  "Health Centre",
  "Posto de Saúde",
  "Centro de Saúde",
  "Clinic",
  "Centre Médical Avec Antenne Chirurgicale",
  "Centre Médico-Chirurgical",
  "Clinique",
  "Centre Medico-Chirurgical"
)

h_other <- c(
  "Hospitais",
  "Cottage Hospital",
  "Polyclinic",
  "Hôpital Coopération",
  "Mission Hospital",
  "Mini Hospital",
  "Hospital Medical Centre",
  "Hospital Medical Center",
  "Polyclinique",
  "Centre Hôpital",
  "Hôpital Comboutique",
  "Hôpital",
  "Hospital"
)

h_dist <- c(
  "District/Provincial Hospital",
  "Centre Hospitalier Départemental",
  "Level 1 Hospital",
  "Centre Hospitalier Préfectoral",
  "Designated District Hospital",
  "Type C Hospital",
  "Type D Hospital",
  "Hospital Distrital",
  "Rural Hospital",
  "Sub-District Hospital",
  "Hôpital Prefectoral",
  "Zonal Hospital",
  "l’Hôpital de Base",
  "Hôpital Préfectoraux",
  "District Hospital",
  "Primary Hospital",
  "Hôpital de Zone",
  "County Hospital",
  "Community Hospital",
  "Hôpital de District",
  "Municipal Hospital"
)

h_ref <- c(
  "Level 3 Hospital",
  "Level 2 Hospital",
  "Regional Referral Hospital",
  "Type B Hospital",
  "Type A Hospital",
  "National Central Hospital",
  "Provincial Tertiary Hospital",
  "Refferal Hospital",
  "State Hospital",
  "Natonal Hospital",
  "University Teaching Hospital",
  "Centre Hospitalier Universitaire",
  "Intermediate Hospital",
  "Hospital Central",
  "Hospital Geral",
  "Hospital Provincial",
  "National Referral Centre",
  "Provincial General Hospital",
  "County Referral Hospital",
  "General Hospital Hospital",
  "Teaching Hospital",
  "Centre Hospitalier Urbain",
  "National Hospital",
  "National Referral Hospital",
  "Tertiary Hospital",
  "Hôpital Général de Référence",
  "Hospitalier Régional",
  "Hospitalier Universitaire",
  "University Hospital",
  "Regional hospital",
  "Hôpital de Regional",
  "Hôpital Régional Universitaire",
  "Hospitais Centrais",
  "Hospitais Regionais",
  "Hôpital Général",
  "Hôpital Centraux",
  "Hôpital Régional",
  "Hôpital Tertiaire",
  "Centre Hospitalier Universitaire National",
  "Centre Hospitalier National",
  "Centre Hospitalier Régional",
  "Referral Hospital",
  "Centre National Hospitalier Universitaire",
  "General Hospital",
  "Regional Hospital",
  "Central Hospital",
  "Provincial Hospital",
  "Hôpital de Nationaux"
)

mch <- c(
  "Maternal & Child Health Centre",
  "Centro Sanatorio Materno Infantil",
  "Centro Materno Infantil",
  "Maternal & Child Health Post"
)
